services:
  bilichat:
    container_name: bilichat
    ports:
      - "8080:8080"
    image: 9ikj/docker-bilichat:latest
    volumes:
      - ./.env:/opt/bilichat/.env
      - ./config.yaml:/opt/bilichat/config.yaml
      - ./nonebot_plugin_bilichat:/root/.local/share/nonebot2/nonebot_plugin_bilichat
    restart: unless-stopped
    